version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
  app:
    build: ./api
    ports:
      - 9000:${PORT}
    depends_on:
      - db
  front:
    build: ./spotiflix
    depends_on:
      - app